# Generated by Django 5.1.2 on 2024-10-24 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmapapi', '0003_alter_assignment_unique_together_milestone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('completed', 'Completed'), ('pending', 'Pending')], max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='milestone',
            unique_together={('name', 'due_date', 'project')},
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('deadline', models.DateField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='roadmapapi.project')),
            ],
            options={
                'unique_together': {('project', 'name')},
            },
        ),
    ]
