# Generated by Django 5.1.2 on 2024-10-24 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmapapi', '0004_alter_milestone_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
