# Generated by Django 5.1.2 on 2024-10-30 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmapapi', '0007_developerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='developerprofile',
            name='available_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='developerprofile',
            name='skills',
            field=models.JSONField(default=list),
        ),
    ]
